### ISSUE TITLE
Docker base image in all docker files

### ISSUE THREAD

**Issue by iperezx** [waggle-sensor/plugin-helloworld-ml#1]
I checked on Dockerhub for FROM waggle/plugin-opencv:4.1.0, but I only see waggle/plugin-opencv:4.1.1. Did you mean to have waggle/plugin-opencv:4.1.1 and not 4.1.0? https://hub.docker.com/r/waggle/plugin-opencv/tags?page=1&ordering=-name

**Comment by gemblerz** [comment]
You are absolutely correct! @seanshahkarami has made the change to fix that (see 02e0d0f90ab87020056797af1109f58d9a03bc77). Thanks for the report!
